"""Second run of treinar_arvore_persistir.py (tree ensemble, persisted predictions).

WHY THERE IS A SECOND RUN (the first-run script is kept unchanged):
  1. The original guard g1 (|diff| <= 0.002 PER SEED) failed at seed 31
     (+0.00275; treinar_arvore_persistir.json, status FALHOU_G1). The rerun
     uses a guard RECALIBRATED BEFORE the rerun:
       g1' (a) mean of the five seeds within 0.002 of the f2_arvores.json
           mean; (b) each seed within 2 x 0.0046 = 0.0092.
  2. This run REUSES the boosters already saved (42, 123, 7,
     2024) and retrains and saves ONLY seed 31. The first run retrained
     all five.
  3. The original's manifest (treinar_arvore_persistir.json, FALHOU_G1) is
     not overwritten: this v2 writes treinar_arvore_persistir_v2.json.

WHAT CHANGES RELATIVE TO THE ORIGINAL (and nothing beyond that):
  - stage 1: for 42/123/7/2024, loads arvore_f2_s7_seed{s}.ubj (no training)
    and checks (guard g1-reuse, fail-loud) that the loaded booster
    reproduces, to 1e-9, the evaluation recorded in the FALHOU_G1 manifest
    (validation/test/holdout skill and MAE) and the same number of trees --
    proof that the file is the booster that passed the check and that data
    loading is deterministic. For seed 31, trains with BA.treinar (identical
    to the original) and saves.
  - guard g1 replaced by g1' (a)+(b) and identical holdout n; on failure ->
    STOPS (exit 2), no grid is produced.
  - stages 2 and 3 (grid prediction, guard g1b, npz + sidecar) copied from
    the original without any change in arithmetic; only the manifest name
    and the "generated by" field change.

Functions reused from the original by IMPORT: skill_de, caminho_npz,
caminho_modelo, fontes_laterais, and the constants (SEEDS, QUADS,
TOL_G1B_*, PREFIXO).

USAGE
  CUDA_VISIBLE_DEVICES="" V23_LATDIR=/trabalho/GNN_TOPO/SATELITES/laterais \
  OMP_NUM_THREADS=12 /trabalho/ambientes/s33_amb_virtual/.venv/bin/python \
      treinar_arvore_persistir_v2.py
"""
from __future__ import annotations

import gc
import json
import os
import sys
import time
from pathlib import Path

import numpy as np

RAIZ = Path(__file__).resolve().parent
sys.path.insert(0, str(RAIZ))

import treinar_arvore_persistir as T0   # noqa: E402  (environment guard runs on import)
import proveniencia as PROV             # noqa: E402
import braco_arvores as BA              # noqa: E402
import b2_transferencia as B2           # noqa: E402

SEEDS = T0.SEEDS                        # [42, 123, 7, 2024, 31], same order as the first run
REAPROVEITAR = [42, 123, 7, 2024]
RETREINAR = [31]
QUADS = T0.QUADS
TOL_G1L_MEDIA = 0.002                   # g1'(a): mean over five seeds
TOL_G1L_SEMENTE = 2 * 0.0046            # g1'(b) = 0.0092 per seed (twice the seed sd of 0.0046)
TOL_REUSO = 1e-9
MANIFESTO_FALHO = T0.MANIFESTO          # first-run manifest (failed the per-seed g1 guard), read only
MANIFESTO = RAIZ / "treinar_arvore_persistir_v2.json"
SHA_MANIFESTO_FALHO = "b028e3b32e0479cfecb038286ab5247b85aa0c4f5607188b469b08338c3c8213"
SHA_BOOSTERS = {   # sha256 of the four reused boosters, recorded before this run
    42: "7101055896d9122a954b185f3f25d54f233c6a39aaf21bc0f2f1479a2e539e52",
    123: "1e663e5eaf5d6864ec6bd794ad1466ab299aea76cd7442a1573ec50318d9aa25",
    7: "c20835fadd68f791ce400c2d5455de5c0e08f14b20b3c24db0944d9f149f15a9",
    2024: "bc020ec572d962457c6b0130a5fa100a14aa637df2074372ef31d6f160027973",
}

log = T0.log


def gravar_manifesto(corpo: dict, fontes: list) -> None:
    prov = PROV.bloco(__file__)
    prov["comando"] = " ".join([sys.executable] + sys.argv)
    prov["ambiente"] = {k: os.environ.get(k) for k in
                        ("V23_LATDIR", "CUDA_VISIBLE_DEVICES", "OMP_NUM_THREADS")}
    saida = {"_proveniencia": prov, "_fontes": PROV.fontes(fontes), **corpo}
    MANIFESTO.write_text(json.dumps(saida, indent=2, ensure_ascii=False,
                                    default=float), encoding="utf-8")


def conferir_reuso(s: int, r: dict, n_arv: int, falho: dict) -> dict:
    """guard g1-reuse: the loaded booster reproduces the evaluation recorded in the FALHOU_G1 manifest."""
    ref = falho["g1"][str(s)]
    difs = {}
    for k in ("validacao", "teste", "reserva"):
        for met in ("skill_media_ponderada_por_n", "mae_media_ponderada_por_n_m"):
            difs[f"{k}.{met}"] = r[k][met] - ref["avaliacao"][k][met]
    dmax = max(abs(v) for v in difs.values())
    ok = bool(dmax <= TOL_REUSO and n_arv == ref["arvores_finais"]
              and r["reserva"]["n"] == ref["n_reserva"])
    return {"max_abs_dif_vs_manifesto_17h": dmax, "arvores": n_arv,
            "arvores_manifesto_17h": ref["arvores_finais"], "tolerancia": TOL_REUSO,
            "passou": ok}


def main() -> int:
    import xgboost as xgb
    t0 = time.time()

    f2 = json.loads(T0.F2_JSON.read_text(encoding="utf-8"))
    cfg = f2["config"]
    cfg_arq = json.loads(T0.F2_CFG.read_text(encoding="utf-8"))["config"]
    if cfg != cfg_arq:
        raise RuntimeError(f"config de f2_arvores.json {cfg} != f2_arvores_config.json {cfg_arq}")
    boost = float(f2["contrato"]["boost"])
    if PROV.sha256(MANIFESTO_FALHO) != SHA_MANIFESTO_FALHO:
        raise RuntimeError(f"{MANIFESTO_FALHO.name} mudou desde a parada das 18:04")
    falho = json.loads(MANIFESTO_FALHO.read_text(encoding="utf-8"))
    for s, h in SHA_BOOSTERS.items():
        hh = PROV.sha256(T0.caminho_modelo(s))
        if hh != h:
            raise RuntimeError(f"booster seed {s}: sha256 {hh} != {h}")
    if T0.caminho_modelo(31).exists():
        raise RuntimeError("arvore_f2_s7_seed31.ubj ja existe: nao sobrescrevo")
    log(f"config (sem busca) {cfg} | boost {boost:g} | nthread {BA.NTHREAD} | "
        f"reaproveitar {REAPROVEITAR} | retreinar {RETREINAR}")

    fontes = [T0.F2_JSON, T0.F2_CFG, MANIFESTO_FALHO, RAIZ / "braco_arvores.py",
              RAIZ / "b2_transferencia.py", RAIZ / "vetor_v23.py", RAIZ / "topo_v23.py",
              RAIZ / "grade_v23.py", RAIZ / "regime.py", RAIZ / "treinar_arvore_persistir.py",
              Path(__file__)] + [T0.caminho_modelo(s) for s in REAPROVEITAR] + T0.fontes_laterais()

    modelos, labs, ys, pred_res, g1l, reuso = {}, {}, {}, {}, {}, {}
    # -- stage 1: load (4) or train (1) + guard g1-reuse + g1'(b) per seed
    for s in SEEDS:
        ts = time.time()
        pecas = BA.carregar_tudo(s, boost)
        if s in REAPROVEITAR:
            m = xgb.Booster()
            m.load_model(str(T0.caminho_modelo(s)))
            m.set_param({"nthread": BA.NTHREAD})
            origem = "reaproveitado (" + T0.caminho_modelo(s).name + ")"
        else:
            m = BA.treinar(pecas, cfg, seed=s)
            origem = "retreinado 28/09 (retomada)"
        r = {"validacao": BA.avaliar(m, pecas, 1),
             "teste": BA.avaliar(m, pecas, 2),
             "reserva": BA.avaliar(m, pecas, 3)}
        n_arv = int(m.num_boosted_rounds())
        if s in REAPROVEITAR:
            reuso[str(s)] = conferir_reuso(s, r, n_arv, falho)
            if not reuso[str(s)]["passou"]:
                gravar_manifesto({"status": "FALHOU_REUSO", "semente": s, "reuso": reuso},
                                 fontes)
                log(f"GUARDA g1-reuso FALHOU seed {s}: {reuso[str(s)]}")
                return 2
        ref = f2["por_semente"][str(s)]
        dif = {k: r[k]["skill_media_ponderada_por_n"] - ref[k]["skill_media_ponderada_por_n"]
               for k in ("validacao", "teste", "reserva")}
        dif_mae = {k: r[k]["mae_media_ponderada_por_n_m"] - ref[k]["mae_media_ponderada_por_n_m"]
                   for k in ("validacao", "teste", "reserva")}
        n_ok = r["reserva"]["n"] == ref["reserva"]["n"]
        passou_b = bool(abs(dif["reserva"]) <= TOL_G1L_SEMENTE and n_ok)
        g1l[str(s)] = {"origem": origem,
                       "skill_reserva": r["reserva"]["skill_media_ponderada_por_n"],
                       "skill_reserva_f2": ref["reserva"]["skill_media_ponderada_por_n"],
                       "dif_skill_reserva": dif["reserva"],
                       "n_reserva": r["reserva"]["n"], "n_reserva_f2": ref["reserva"]["n"],
                       "dif_skill_validacao": dif["validacao"], "dif_skill_teste": dif["teste"],
                       "dif_mae_m": dif_mae, "arvores_finais": n_arv,
                       "avaliacao": r, "tolerancia_b": TOL_G1L_SEMENTE, "passou_b": passou_b,
                       "segundos": round(time.time() - ts, 1)}
        if s in RETREINAR and str(s) in falho["g1"]:
            prev = falho["g1"][str(s)]
            g1l[str(s)]["descritivo_vs_retreino_18h04"] = {
                "skill_reserva_18h04": prev["skill_reserva"],
                "dif": r["reserva"]["skill_media_ponderada_por_n"] - prev["skill_reserva"],
                "arvores_18h04": prev["arvores_finais"],
                "nota": "so descritivo (determinismo do retreino); nao e guarda"}
        log(f"seed {s} [{origem}]: skill reserva {r['reserva']['skill_media_ponderada_por_n']:+.6f} "
            f"(f2 {ref['reserva']['skill_media_ponderada_por_n']:+.6f}, dif {dif['reserva']:+.2e}) "
            f"n {r['reserva']['n']} | arvores {n_arv} | g1'(b) {'PASSOU' if passou_b else 'FALHOU'}"
            + (f" | reuso max|dif| {reuso[str(s)]['max_abs_dif_vs_manifesto_17h']:.1e}"
               if s in REAPROVEITAR else "") + f" | {time.time()-ts:.0f} s")
        if not passou_b:
            gravar_manifesto({"status": "FALHOU_G1_LINHA_B", "semente_que_falhou": s,
                              "config": cfg, "boost": boost, "g1_linha": g1l, "reuso": reuso,
                              "nota": "g1'(b) falhou: nenhuma grade foi predita nem gravada"},
                             fontes)
            log(f"GUARDA g1'(b) FALHOU na semente {s}: PARANDO")
            return 2
        if s in RETREINAR:
            m.save_model(str(T0.caminho_modelo(s)))
        modelos[s] = m
        labs[s] = {q: pecas[q]["lab"].copy() for q in QUADS}
        ys[s] = {q: pecas[q]["y"].copy() for q in QUADS}
        pred_res[s] = {q: m.predict(xgb.DMatrix(pecas[q]["X"][pecas[q]["lab"] == 3]))
                       for q in QUADS}
        del pecas
        gc.collect()

    # -- g1'(a): mean of the five seeds
    sk = [g1l[str(s)]["skill_reserva"] for s in SEEDS]
    media = float(np.mean(sk))
    f2_media_arq = float(f2["resumo"]["skill_reserva_media"])
    f2_media_rec = float(np.mean([f2["por_semente"][str(s)]["reserva"]["skill_media_ponderada_por_n"]
                                  for s in SEEDS]))
    dif_media = media - f2_media_arq
    passou_a = bool(abs(dif_media) <= TOL_G1L_MEDIA)
    g1l_a = {"skill_media_5": media, "skill_dp_5": float(np.std(sk, ddof=1)),
             "f2_skill_media": f2_media_arq, "f2_skill_media_recalculada_por_semente": f2_media_rec,
             "f2_skill_dp": float(f2["resumo"]["skill_reserva_dp"]),
             "dif_media": dif_media, "tolerancia_a": TOL_G1L_MEDIA, "passou_a": passou_a,
             "max_abs_dif_por_semente": float(max(abs(g1l[str(s)]["dif_skill_reserva"]) for s in SEEDS)),
             "tolerancia_b": TOL_G1L_SEMENTE,
             "passou_b_todas": bool(all(g1l[str(s)]["passou_b"] for s in SEEDS))}
    log(f"g1'(a): media {media:+.6f} f2 {f2_media_arq:+.6f} dif {dif_media:+.2e} "
        f"(tol {TOL_G1L_MEDIA}) -> {'PASSOU' if passou_a else 'FALHOU'} | "
        f"g1'(b) max|dif| {g1l_a['max_abs_dif_por_semente']:.2e} (tol {TOL_G1L_SEMENTE})")
    if abs(f2_media_rec - f2_media_arq) > 1e-12:
        raise RuntimeError(f"resumo do f2 {f2_media_arq} != media das sementes {f2_media_rec}")
    if not passou_a:
        gravar_manifesto({"status": "FALHOU_G1_LINHA_A", "config": cfg, "boost": boost,
                          "g1_linha": g1l, "g1_linha_a": g1l_a, "reuso": reuso,
                          "nota": "g1'(a) falhou: nenhuma grade foi predita nem gravada"}, fontes)
        log("GUARDA g1'(a) FALHOU: PARANDO")
        return 2

    # -- stage 2: prediction over the whole grid (copied from the original, same arithmetic)
    campos = {s: {} for s in SEEDS}
    diag = {s: {} for s in SEEDS}
    g1b = {str(s): {"max_abs_dif_pred_reserva_m": 0.0} for s in SEEDS}
    preds_grade_res = {s: {} for s in SEEDS}
    for q in QUADS:
        tq = time.time()
        dd, _lab, prep, _ = B2.preparar_peca(
            "amazonia", q, SEEDS[0], B2.BLOCO, "v23",
            True, True, False, False, False, True)      # same arguments as BA.carregar_tudo
        del prep, _lab
        gc.collect()
        X, idx = dd["X"], np.asarray(dd["idx"])
        n = int(dd["n_nodes"])
        if X.shape[0] != n:
            raise RuntimeError(f"{q}: X tem {X.shape[0]} linhas, n_nodes {n}")
        dsm = np.load(Path(T0.LATDIR_ESPERADO) / f"glo30_amazonia_{q}.npz")["DEM"].astype(np.float32)
        dm = xgb.DMatrix(X)
        log(f"{q}: X {X.shape} carregado em {time.time()-tq:.0f} s")
        for s in SEEDS:
            if len(labs[s][q]) != len(idx):
                raise RuntimeError(f"{q}/seed {s}: lab {len(labs[s][q])} != idx {len(idx)}")
            tp = time.time()
            out = modelos[s].predict(dm).astype(np.float32)
            if out.shape != (n,):
                raise RuntimeError(f"{q}/seed {s}: predicao {out.shape} != ({n},)")
            pr = out[idx][labs[s][q] == 3]
            dmax = float(np.max(np.abs(pr - pred_res[s][q]))) if pr.size else 0.0
            g1b[str(s)]["max_abs_dif_pred_reserva_m"] = max(
                g1b[str(s)]["max_abs_dif_pred_reserva_m"], dmax)
            if dmax > T0.TOL_G1B_PRED:
                raise RuntimeError(f"GUARDA g1b FALHOU {q}/seed {s}: predicao da grade nos nos "
                                   f"de reserva difere da do treino em {dmax} m (> {T0.TOL_G1B_PRED})")
            preds_grade_res[s][q] = pr
            campos[s][q] = out
            z = dsm - out
            diag[s][q] = {
                "delta_mediano_m": round(float(np.median(out)), 4),
                "delta_p5_m": round(float(np.percentile(out, 5)), 4),
                "delta_p95_m": round(float(np.percentile(out, 95)), 4),
                "frac_delta_negativo_todas_celulas": round(float((out < 0).mean()), 6),
                "z_min_m": round(float(z.min()), 3),
                "z_max_m": round(float(z.max()), 3)}
            del z
            log(f"  {q} seed {s}: {time.time()-tp:.0f} s | Delta mediano {np.median(out):.3f} m "
                f"| max|dif| reserva {dmax:.2e}")
        del dd, X, dm, dsm
        gc.collect()

    for s in SEEDS:
        sk_g = T0.skill_de(preds_grade_res[s], ys[s], labs[s])
        d = sk_g - g1l[str(s)]["skill_reserva"]
        g1b[str(s)].update({"skill_reserva_da_grade": sk_g, "dif_vs_avaliar": d,
                            "passou": bool(abs(d) <= T0.TOL_G1B_SKILL)})
        if abs(d) > T0.TOL_G1B_SKILL:
            raise RuntimeError(f"GUARDA g1b FALHOU seed {s}: skill da grade {sk_g} != avaliar "
                               f"{g1l[str(s)]['skill_reserva']} (dif {d})")
    log("guarda g1b: PASSOU nas 5 sementes")

    # -- stage 3: write npz + sidecar with sha256 (same as the first run)
    artefatos = {}
    for s in SEEDS:
        p = T0.caminho_npz(s)
        if p.exists():
            raise RuntimeError(f"{p.name} ja existe: nao sobrescrevo")
        np.savez(p, **{q: campos[s][q] for q in QUADS})
        h = PROV.sha256(p)
        side = {"bioma": "amazonia", "modo": "arvore_f2_s7", "seed": s, "arm": "xgboost_f2",
                "conteudo": "Delta em metros por quadrante; z' = glo30 - Delta",
                "modelo": T0.caminho_modelo(s).name,
                "sha256_modelo": PROV.sha256(T0.caminho_modelo(s)),
                "origem_modelo": g1l[str(s)]["origem"],
                "config": cfg, "boost": boost, "suavidade": 0.0,
                "npz": p.name, "sha256_npz": h, "bytes_npz": p.stat().st_size,
                "quadrantes": diag[s],
                "gerado_por": Path(__file__).name,
                "sha256_script": PROV.sha256(Path(__file__))}
        p.with_suffix(".json").write_text(json.dumps(side, indent=2, ensure_ascii=False),
                                          encoding="utf-8")
        artefatos[str(s)] = {"npz": p.name, "sha256_npz": h, "sidecar": p.with_suffix(".json").name,
                             "modelo": T0.caminho_modelo(s).name,
                             "sha256_modelo": side["sha256_modelo"],
                             "origem_modelo": g1l[str(s)]["origem"]}
        log(f"-> {p.name} sha256 {h[:16]}... ({p.stat().st_size/2**20:.0f} MB)")

    gravar_manifesto({
        "status": "OK",
        "desenho": ("Pre-declared design note, sections S7 and 'S7 -- resumption' (g1' "
                    "recalibrated before the resumption)"),
        "config": cfg, "boost": boost, "suavidade": 0.0, "sementes": SEEDS,
        "reaproveitadas": REAPROVEITAR, "retreinadas": RETREINAR,
        "nthread_xgboost": BA.NTHREAD,
        "g1_linha": g1l, "g1_linha_a": g1l_a, "reuso": reuso, "g1b": g1b,
        "resumo_reserva": {"skill_media": media, "skill_dp": g1l_a["skill_dp_5"],
                           "f2_skill_media": f2_media_arq, "f2_skill_dp": g1l_a["f2_skill_dp"]},
        "artefatos": artefatos,
        "manifesto_da_parada": {"arquivo": MANIFESTO_FALHO.name, "sha256": SHA_MANIFESTO_FALHO,
                                "status": falho.get("status")},
        "formato": "igual a superficies/delta_amazonia_ampliacao_b4s035*_seed*.npz: chaves Q1..Q4, "
                   "float32, 12.960.000 nos (3600x3600), Delta em metros; agregacao entre sementes "
                   "e feita pelo auditor (media de 5, como juiz_lidar_v4.montar)",
        "segundos_total": round(time.time() - t0, 1),
    }, fontes)
    log(f"-> {MANIFESTO.name} ({time.time()-t0:.0f} s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
